#!/bin/bash
# Scripty script

python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 255 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 26 -rn 3 -rl 3 -bt 24 -os 30 -bs 8 -ns 512 -rp 3 -sc 2
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 256 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 26 -rn 3 -rl 3 -bt 24 -os 30 -bs 8 -ns 512 -rp 3 -sc 6
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 257 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 26 -rn 3 -rl 3 -bt 24 -os 30 -bs 8 -ns 512 -rp 3 -sc 60
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 258 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 26 -rn 3 -rl 3 -bt 24 -os 30 -bs 8 -ns 512 -rp 6 -sc 2
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 259 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 26 -rn 3 -rl 3 -bt 24 -os 30 -bs 8 -ns 512 -rp 6 -sc 6
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 260 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 26 -rn 3 -rl 3 -bt 24 -os 30 -bs 8 -ns 512 -rp 6 -sc 60
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 261 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 26 -rn 3 -rl 3 -bt 24 -os 30 -bs 8 -ns 512 -rp 12 -sc 2
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 262 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 26 -rn 3 -rl 3 -bt 24 -os 30 -bs 8 -ns 512 -rp 12 -sc 6
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 263 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 26 -rn 3 -rl 3 -bt 24 -os 30 -bs 8 -ns 512 -rp 12 -sc 60
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 264 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 27 -rn 3 -rl 3 -bt 24 -os 30 -bs 8 -ns 512 -rp 3 -sc 2
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 265 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 27 -rn 3 -rl 3 -bt 24 -os 30 -bs 8 -ns 512 -rp 3 -sc 6
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 266 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 27 -rn 3 -rl 3 -bt 24 -os 30 -bs 8 -ns 512 -rp 3 -sc 60
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 267 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 27 -rn 3 -rl 3 -bt 24 -os 30 -bs 8 -ns 512 -rp 6 -sc 2
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 268 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 27 -rn 3 -rl 3 -bt 24 -os 30 -bs 8 -ns 512 -rp 6 -sc 6
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 269 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 27 -rn 3 -rl 3 -bt 24 -os 30 -bs 8 -ns 512 -rp 6 -sc 60
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 270 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 27 -rn 3 -rl 3 -bt 24 -os 30 -bs 8 -ns 512 -rp 12 -sc 2
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 271 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 27 -rn 3 -rl 3 -bt 24 -os 30 -bs 8 -ns 512 -rp 12 -sc 6
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 272 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 27 -rn 3 -rl 3 -bt 24 -os 30 -bs 8 -ns 512 -rp 12 -sc 60
