#!/bin/bash
# Scripty script

python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 450 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 20 -rn 3 -rl 2 -bt 24 -os 30 -bs 8 -ns 512
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 451 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 20 -rn 3 -rl 2 -bt 24 -os 20 -bs 8 -ns 512
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 452 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 20 -rn 3 -rl 2 -bt 24 -os 10 -bs 8 -ns 512
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 453 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 20 -rn 3 -rl 2 -bt 16 -os 20 -bs 8 -ns 512
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 454 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 20 -rn 3 -rl 2 -bt 36 -os 20 -bs 8 -ns 512
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 455 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 20 -rn 3 -rl 2 -bt 24 -os 20 -bs 8 -ns 1024
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 456 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 20 -rn 3 -rl 2 -bt 24 -os 20 -bs 8 -ns 256
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 457 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 21 -rn 3 -rl 2 -bt 24 -os 30 -bs 8 -ns 512
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 458 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 21 -rn 3 -rl 2 -bt 24 -os 20 -bs 8 -ns 512
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 459 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 21 -rn 3 -rl 2 -bt 24 -os 10 -bs 8 -ns 512
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 460 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 21 -rn 3 -rl 2 -bt 16 -os 20 -bs 8 -ns 512
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 461 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 21 -rn 3 -rl 2 -bt 36 -os 20 -bs 8 -ns 512
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 462 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 21 -rn 3 -rl 2 -bt 24 -os 20 -bs 8 -ns 1024
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 463 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 21 -rn 3 -rl 2 -bt 24 -os 20 -bs 8 -ns 256
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 464 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 22 -rn 3 -rl 2 -bt 24 -os 30 -bs 8 -ns 512
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 465 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 22 -rn 3 -rl 2 -bt 24 -os 20 -bs 8 -ns 512
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 466 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 22 -rn 3 -rl 2 -bt 24 -os 10 -bs 8 -ns 512
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 467 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 22 -rn 3 -rl 2 -bt 16 -os 20 -bs 8 -ns 512
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 468 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 22 -rn 3 -rl 2 -bt 36 -os 20 -bs 8 -ns 512
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 469 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 22 -rn 3 -rl 2 -bt 24 -os 20 -bs 8 -ns 1024
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 470 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 3000 -t 10000000 -m 1000 -s modelSave -sd 22 -rn 3 -rl 2 -bt 24 -os 20 -bs 8 -ns 256
