#!/bin/bash
# Scripty script

python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 1 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 20 -rn 3 -rl 3 -bt 48 -os 30 -bs 8 -ns 512 -rp 16 -sc 6
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 1 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 20 -rn 2 -rl 3 -bt 48 -os 30 -bs 8 -ns 512 -rp 16 -sc 6
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 1 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 20 -rn 1 -rl 3 -bt 48 -os 30 -bs 8 -ns 512 -rp 16 -sc 6
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 1 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 20 -rn 3 -rl 2 -bt 48 -os 30 -bs 8 -ns 512 -rp 16 -sc 6
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 1 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 20 -rn 2 -rl 2 -bt 48 -os 30 -bs 8 -ns 512 -rp 16 -sc 6
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 1 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 20 -rn 1 -rl 2 -bt 48 -os 30 -bs 8 -ns 512 -rp 16 -sc 6
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 1 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 20 -rn 3 -rl 1 -bt 48 -os 30 -bs 8 -ns 512 -rp 16 -sc 6
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 1 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 20 -rn 2 -rl 1 -bt 48 -os 30 -bs 8 -ns 512 -rp 16 -sc 6
python3 /home/adf/exp715/Box2dEnv/Box2dEnv/TuneScript-1L.py 1 EnvTestContinuousR-v2 -a 900-ppo.json -n 900-mlp2_network.json -e 2000 -t 10000000 -m 1000 -s modelSave -sd 20 -rn 1 -rl 1 -bt 48 -os 30 -bs 8 -ns 512 -rp 16 -sc 6



